### PR TITLE
Avoid corrupting documents when tracking destroy

### PR DESCRIPTION
**Pull request by dgknght**
If an embedded document has its version incremented, but an ancester
is flagged for destroy and the root document is not, then this causes
conflicts, which are written to the otherwise empty embedded document,
leaving a corrupt document in storage.

Note that this only happens with the parent document cascades
callbacks.

### CODE REVIEW

**Comment by cgriego** [comment]
The way I read this change is that we stop recording history records when deleting nested records, which isn't functionality we should remove. Is there an existing test showing that we still record these?

**Comment by cgriego** [comment]
This looks better. My final concern is that we're now recording history tracks with the same version when something is destroyed. The library expects these to be unique/sequential and it uses these for sorting and for the undo/redo functionality. I think we can appease that by ensuring we write an incremented value on destroy without incrementing the version field on the original document.

**Review by cgriego — APPROVED** [review]
This functionality looks right to me. May want to enhances the tests some.

**Comment by dgknght** [comment]
Moving to a new PR for the upstream repo

**Pull request closed without merging**
